### ISSUE TITLE
Wrong extension detection if path includes folder name

### ISSUE THREAD

**Issue by vorg** [dmnsgn/canvas-screenshot#9]
I was wondering why my jpg files are actually png inside and it turns out that...

```javascript
var fileExtension = require("file-extension")
console.log(fileExtension("bla.jpg")) -> 'jpg'
console.log(fileExtension("bla\bla.jpg")) -> 'undefined'
```

**Comment by vorg** [comment]
Actually issue was somewhere else as i was using toBlob and not providing file name...

**Comment by dmnsgn** [comment]
Closing as filenames assigned to the html link element download property can't be path.
